"""Helpers for IN21k dense-feature policy pretraining."""

from canvit_rl.pretrain_IN21k.dense_train_batch import (
    DenseTrainBatch,
    FixedDenseSubsetLoader,
    PairedDenseShardLoader,
    apply_dense_feature_config,
    dense_glimpse_images,
    init_normalizer_stats_from_shard,
    load_dense_train_batch,
    validate_dense_feature_source,
)
from canvit_rl.pretrain_IN21k.pretrain_modules import (
    install_pretrain_train_shim,
    load_pretrain_modules,
)
from canvit_rl.pretrain_IN21k.reward import (
    DenseDistillationMetrics,
    dense_distillation_metrics,
    dense_loss_clipped_l0_delta_reward,
    dense_loss_delta_reward,
    dense_loss_l0_delta_reward,
    dense_loss_log_delta_clipped_reward,
    dense_loss_log_delta_tanh_reward,
    dense_loss_log_delta_reward,
    dense_loss_reduction_reward,
    dense_loss_tanh_l0_delta_reward,
    dense_raw_mse_clipped_l0_delta_reward,
    dense_raw_mse_delta_reward,
    dense_raw_mse_l0_delta_reward,
    dense_raw_mse_log_delta_clipped_reward,
    dense_raw_mse_log_delta_tanh_reward,
    dense_raw_mse_log_delta_reward,
    dense_raw_mse_reduction_reward,
    dense_raw_mse_tanh_l0_delta_reward,
    dense_reward,
)

__all__ = [
    "DenseDistillationMetrics",
    "DenseTrainBatch",
    "FixedDenseSubsetLoader",
    "PairedDenseShardLoader",
    "apply_dense_feature_config",
    "dense_glimpse_images",
    "dense_distillation_metrics",
    "dense_loss_clipped_l0_delta_reward",
    "dense_loss_delta_reward",
    "dense_loss_l0_delta_reward",
    "dense_loss_log_delta_clipped_reward",
    "dense_loss_log_delta_tanh_reward",
    "dense_loss_log_delta_reward",
    "dense_loss_reduction_reward",
    "dense_loss_tanh_l0_delta_reward",
    "dense_raw_mse_clipped_l0_delta_reward",
    "dense_raw_mse_delta_reward",
    "dense_raw_mse_l0_delta_reward",
    "dense_raw_mse_log_delta_clipped_reward",
    "dense_raw_mse_log_delta_tanh_reward",
    "dense_raw_mse_log_delta_reward",
    "dense_raw_mse_reduction_reward",
    "dense_raw_mse_tanh_l0_delta_reward",
    "dense_reward",
    "init_normalizer_stats_from_shard",
    "install_pretrain_train_shim",
    "load_dense_train_batch",
    "load_pretrain_modules",
    "validate_dense_feature_source",
]
